---


services:

  app:
    image: b4bz/homer:latest
    restart: always
    user: 1000:1000
    ports:
      - "{{ homer_port }}:{{ homer_port }}"
    volumes:
      - "{{ basedir }}/assets:/www/assets"
    environment:
      - INIT_ASSETS=1
      - PORT={{ homer_port }}
