---

# set general sysctl.conf settings
# the module will reload the setting so they are applied without reboot

- name: Get facts on current container
  community.docker.current_container_facts:

- name: set vm.swappiness to minimize usage of swap 
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present
  when: ansible_module_running_in_container == ""
