# Loads default set of integrations. Do not remove.
default_config:

# includes
# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:  
  name: "streiner-home"
  latitude: 51.97700
  longitude: 7.41332
  elevation: 70
  unit_system: metric
  currency: EUR 
  country: DE
  time_zone: Europe/Berlin
  internal_url: http://{{ int_ip4 }}:{{ homassistant_port }}
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - {{ networks.local.cdir_v4 }}
        # Teamp: Netzwerk chris für Konfiguration
        - 10.0.0.0/8 
      allow_bypass_login: true
    - type: homeassistant

# https://www.home-assistant.io/integrations/http/
http:
  server_port: 8123
  ip_ban_enabled: False
  login_attempts_threshold: 10

# https://www.home-assistant.io/integrations/api/
api:

# https://www.home-assistant.io/integrations/logger
# log_level= critical, fatal, error, warning, warn, info, debug, notset
logger:
  default: info

# https://www.home-assistant.io/integrations/influxdb/
influxdb:
  api_version: 2 
  host: influxdb
  port: 8086 
  ssl: false
  organization: homeassistant
  bucket: homeassistant
  token: {{ influxdb_token }}
  default_measurement: units

