---
# Pakete installieren
- name: pakete installieren
  apt:
    update_cache: yes
    state: present
    name:
      - prometheus-node-exporter

- name: remove old directories 
  file: 
    path: "{{ item }}"
    state: "absent"
  with_items:
    - /srv/prometheus-node-exporter 

- name: Configure Node-Exporter 
  lineinfile:
    path: /etc/default/prometheus-node-exporter
    regexp: '^ARGS='
    line: ARGS="--web.listen-address={{int_ip4}}:9100"

- name: reload systemd and enable service
  command: systemctl enable prometheus-node-exporter

- name: restart prometheus-node-exporter
  service: 
    name: prometheus-node-exporter 
    state: restarted
