

services:

  app:

    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "{{ web_port }}:{{ web_port }}/tcp"
    volumes:
      - '{{ basedir }}/etc:/etc/pihole'
      - '{{ basedir }}/dnsmasq:/etc/dnsmasq.d'
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_LOCAL_IPV4: '{{ int_ip4 }}'
      WEBPASSWORD: '{{ admin_password }}'
      WEB_PORT: {{ web_port }}
