

services:

  app:
    image: ghcr.io/freifunkmuc/wg-access-server:latest
    restart: always
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    volumes:
      - "{{ basedir }}/data:/data"
    ports:
      - "{{ vpn_port }}:{{ vpn_port }}/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - "WG_ADMIN_USERNAME=vpnadmin"
      - "WG_ADMIN_PASSWORD={{ wg_admin_pass }}"
      - "WG_WIREGUARD_PRIVATE_KEY={{ wg_private_key }}"
      - "WG_WIREGUARD_PORT={{ vpn_port }}"
      - "WG_VPN_CIDR={{ networks.vpnserver.cdir_v4 }}"
      - "WG_VPN_CIDRV6=0" # to disable IPv6
      - "WG_VPN_ALLOWED_IPS={{ networks.defaultroute.cdir_v4 }}, {{ networks.vpnserver.cdir_v4 }}, {{ networks.vpnserver.dns.server | ansible.utils.ipaddr('host') }}, {{ networks.local.cdir_v4 }}, {{ networks.webserver1.cdir_v4 }}, {{ networks.webserver2.cdir_v4 }}" 
      - "WG_EXTERNAL_HOST={{ domain }}"
      - "WG_DNS_ENABLED=true"
      - "WG_DNS_DOMAIN={{ networks.vpnserver.dns.domain }}"
      - "WG_DNS_UPSTREAM={{ networks.vpnserver.dns.server }}"
      - "WG_LOG_LEVEL=info"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=8000
    networks:
      - default
      - web


networks:
  web:
    external: true
