       
- include_tasks: ../functions/get_secret.yml
  with_items:
    - { path: "{{ basedir }}/admin_password",  length: 24 }

- name: "create folder struct for {{ servicename }}"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/etc"
    - "{{ basedir }}/dnsmasq"

- name: "create config files for {{ servicename }}"
  template:
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml
  register: config

- name: "stop {{ servicename}} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config.changed

- name: "start {{ servicename}} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
