

- include_tasks: ../functions/get_secret.yml
  with_items:
    - { path: "{{ basedir }}/grafana_admin_pass", length: 12 }
    - { path: "/srv/homeassistant/influxdb_token", length: -1 } 

- name: get homeassistant influxdb token 1
  slurp: 
    src: /srv/homeassistant/influxdb_token
  register: homeassistant_influxdb_token_slurp

- name: get homeassistant influxdb token 2
  set_fact: 
    "homeassistant_influxdb_token": "{{ homeassistant_influxdb_token_slurp.content | b64decode | regex_replace('\\s', '') }}" 

- name: create folder struct for grafana
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/data/"   
    - "{{ basedir }}/provisioning/"
    - "{{ basedir }}/provisioning/datasources/"

- name: create config filess
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - grafana.ini
    - provisioning/datasources/datasources.yml

- name: start grafana docker
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
