
services:

    app:
        image: traefik:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "{{ int_ip4 }}:8080:8080"
        volumes:
            - "{{ basedir }}/traefik.yml:/etc/traefik/traefik.yml:ro"
            - "{{ basedir }}/dynamic:/etc/traefik/dynamic:ro"
            - "{{ basedir }}/acme.json:/acme.json"
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - default
            - web
        healthcheck:
            test: ['CMD', 'traefik', 'healthcheck']
            interval: 30s
            timeout: 10s
            retries: 3

# for debugging only            
#    whoami:
#        image: containous/whoami
#        labels:
#            - traefik.enable=true
#            - traefik.http.routers.{{ servicename }}.rule=Host(`{ domain }`)
#            - traefik.http.routers.{{ servicename }}.entrypoints=websecure
#            - traefik.http.services.{{ servicename }}.loadbalancer.server.port=80
#        networks:
#            - web

networks:
  web:
    external: true    
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        # must be a ULA range
        - subnet: fd00:dead:beef:80::/64