---

- name: install deb packages
  apt:
    update_cache: yes
    state: present
    install_recommends: no
    name:
      - apparmor
      - docker-ce
      - docker-compose-plugin
      - gnupg2 
      - pass 
      - python3 
      - python3-docker
      - python3-pip
      - python3-setuptools


- name: daemon config für docker erstellen 
  template: src=daemon.json dest=/etc/docker/daemon.json
  notify: restart docker


- name: Cronjob to prune unused images  
  cron: name="docker-prune" weekday="*" hour="5" minute="5" job="/usr/bin/docker system prune --volumes --all -f"  

- name: "Set Docker Server Blocker file: {{ docker.service_blocker_file }}"
  ini_file:
    path: "{{ item }}"
    section: Unit
    option: ConditionFileNotEmpty
    value: "{{ docker.service_blocker_file }}"
    backup: yes
  with_items: 
    - /lib/systemd/system/containerd.service 
    - /lib/systemd/system/docker.service 
    - /lib/systemd/system/docker.socket
  when: docker.service_blocker_file is defined 

- name: force systemd to reread configs 
  systemd:
    daemon_reload: yes

- name: "Create internal Networks: {{ docker.internal_networks }}"
  docker_network:
    name: "{{ item }}"
    internal: yes
  with_items: "{{ docker.internal_networks }}"
  when: docker.internal_networks is defined and docker.internal_networks|length > 0
