---

- include_tasks: ../functions/get_secret.yml
  with_items:
   - { path: "{{ basedir }}/homeassistant_admin_password", type: create, length: 12 }
   - { path: "{{ basedir }}/influxdb_password",            type: create, length: 12 }
   - { path: "{{ basedir }}/influxdb_token",               type: create, length: 32 }


- name: "create folder struct for {{ basedir }}"
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/config/"


- name: "copy config files for {{ basedir }}"
  template:
    src: "{{ item }}"
    dest: "{{ basedir }}/{{ item }}"
  with_items:
    - docker-compose.yml
    - config/configuration.yaml
  register: config_files


- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config_files.changed 


- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
