---

- name: create folder struct for {{ servicename }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "{{ basedir }}"
    - "{{ basedir }}/assets"

- name: copy config files for {{ servicename }}
  ansible.builtin.template:
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
    mode: '0755'
  with_items:
    - docker-compose.yml
    - assets/config.yml
  register: config_files

- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config_files.changed 

- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present
