
services:

  app:

    image: eclipse-mosquitto:2
    restart: always
    ports:
      - {{ mqtt_port }}:1883 
    volumes:
      - {{ basedir }}/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - {{ basedir }}/data:/mosquitto/data
      - {{ basedir }}/log:/mosquitto/log

