
services:

  app:

    image: eclipse-mosquitto:2
    restart: always
    ports:
      - {{ mqtt_port }}:1883 
    volumes:
      - {{ basedir }}/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - {{ basedir }}/data:/mosquitto/data
      - {{ basedir }}/log:/mosquitto/log

  explorer:

    image: smeagolworms4/mqtt-explorer
    restart: always
    ports:
      - {{ explorer_port }}:{{ explorer_port }}
    volumes:
      - {{ basedir }}/settings.json:/mqtt-explorer/config/settings.json:ro
    environment:
      HTTP_PORT: {{ explorer_port }}
      CONFIG_PATH: "/mqtt-explorer/config"
