
services:

  app:

    image: prom/prometheus:latest
    restart: always    
    ports:
      - "{{ prometheus_port }}:9090"
    volumes:
      - "{{ basedir }}/data:/prometheus"
      - "{{ basedir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
    environment:
      PGID: 1001
      PUID: 1001
      MEM_LIMIT: 256


  influxdb:

    image: influxdb:2
    restart: always
    ports:
      - "{{ int_ip4 }}:{{ influxdb_port }}:8086"
    volumes:
      - "{{ basedir }}/influxdb:/var/lib/influxdb2"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: prometheus
      DOCKER_INFLUXDB_INIT_PASSWORD: {{ influxdb_password }}
      DOCKER_INFLUXDB_INIT_ORG: prometheus
      DOCKER_INFLUXDB_INIT_BUCKET: prometheus
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: {{ influxdb_token }}


  snmp:
    image: quay.io/prometheus/snmp-exporter:latest
    restart: always

