
services:

  app:

    image: grafana/grafana:latest
    restart: always
    ports:
      - "{{ grafana_port }}:3000"
    volumes:
      - "{{ basedir }}/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ basedir }}/data/:/var/lib/grafana"
    environment:
      GF_SERVER_ROOT_URL: "http://{{ inventory_hostname }}:{{ grafana_port }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_pass }}"
