
services:

  app:

    image: grafana/grafana:latest
    restart: always
    ports:
      - "{{ grafana_port }}:3000"
    volumes:
      - "{{ basedir }}/grafana.ini:/etc/grafana/grafana.ini"
      - "{{ basedir }}/provisioning/:/etc/grafana/provisioning/"
      - "{{ basedir }}/data/:/var/lib/grafana"

